version: '3.9'
services:
  nodejs:
    restart: on-failure
    build: ./node
    ports:
      - '81:5000'
    networks:
      - app-network
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - nodejs
    networks:
      - app-network
